version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_barbearia
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=barbearia
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=barbearia
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
